import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/website/home/layout/Header";
import Footer from "@/components/website/home/layout/Footer";
import StoreProvider from "@/redux/StoreProvider";
import { getMe } from "@/api/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 

  
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body >
        <StoreProvider>
          <Header  />
          {children}
          <Footer />
        </StoreProvider>
      </body>


    </html >
  );
}